### ISSUE TITLE
python3-eccodes broken on CentOS8

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/python-eccodes-rpm#3]
```
$ python3
Python 3.6.8 (default, Sep 10 2021, 09:13:53) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import eccodes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.6/site-packages/eccodes/__init__.py", line 13, in <module>
    from .eccodes import *  # noqa
  File "/usr/lib64/python3.6/site-packages/eccodes/eccodes.py", line 12, in <module>
    from gribapi import (
  File "/usr/lib64/python3.6/site-packages/gribapi/__init__.py", line 13, in <module>
    from .gribapi import *  # noqa
  File "/usr/lib64/python3.6/site-packages/gribapi/gribapi.py", line 34, in <module>
    from . import errors
  File "/usr/lib64/python3.6/site-packages/gribapi/errors.py", line 16, in <module>
    from .bindings import ENC, ffi, lib
  File "/usr/lib64/python3.6/site-packages/gribapi/bindings.py", line 38, in <module>
    library_path = os.path.join(sys.prefix, sys.platlibdir, 'libeccodes.so')
AttributeError: module 'sys' has no attribute 'platlibdir'
>>> 
```

**Comment by brancomat** [comment]
The issue seems to be that `sys.platlibdir` is available only in python 3.9 and newer:
https://docs.python.org/3/library/sys.html#sys.platlibdir

There's no trace of that call in the sources, it has been introduced by the patch `python-eccodes-disable-findlibs.patch` that tries to avoid a custom dependency from ecmwflibs/findlibs.

The solution could be edit the patchfile (or patch-the-patched-file, if we want to mantain compatibility with fedora specfile) using a solution python 3.6 compatible
